site_name: Observatory (R U OK?) Documentation
site_url: https://phacdatahub.github.io/ruok-service-autochecker/

theme:
  name: material
  palette:
    primary: indigo
    accent: blue

repo_url: https://github.com/PHACDataHub/ruok-service-autochecker

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/PHACDataHub/ruok-service-autochecker 

plugins:
  - search:
      separator: '[\s\-\.]+'
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences

nav:
  - Architecture: architecture.md
  - Data Contracts: data-contracts.md
  - Configuration: configuration.md
  - Deployment: deployment.md
  - Development Environment: development-environment.md
  - GitHub Webhooks: github-webhooks.md
  - GraphQL API: graphql-api.md
  - Scanners: scanners.md
  - Register a Repository: register-repository.md
