apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-endpoint-scanner
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: web-endpoint-scanner
  template:
    metadata:
      labels:
        app: web-endpoint-scanner
    spec:
      containers:
        - name: web-endpoint-scanner
          image: localhost/ruok-web-endpoint-scanner:0.0.1
