apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./arangodeployment-single-server.yaml
- ./deployment-nats.yaml
- ./deployment-ruok-api.yaml
- ./deployment-webhook-server.yaml
- ./deployment-graph-updater.yaml
- ./deployment-octokit-scanner.yaml
- ./svc-nats.yaml
- ./svc-ruok-api.yaml
- ./svc-webhook-server.yaml
patches:
- target:
    version: v1
    kind: Deployment
    name: webhook-server
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: NATS_SERVER
          value: nats:4222
        - name: NATS_PUB_STREAM
          value: EventsUpdate
