apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment.yaml
- ./arango-single-server.yaml
# From arrangodb k8s operator: https://github.com/arangodb/kube-arangodb/tree/master
- https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.33/manifests/arango-crd.yaml
- https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.33/manifests/arango-deployment.yaml