apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: phx-01h8eq9sbx7d19zsvqk7t9zymr
      auth:
        workloadIdentity:
          # name of the cluster Location, region or zone
          clusterLocation: northamerica-northeast1
          # name of the GKE cluster
          clusterName: observatory-cluster
          # reference the sa from above
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
