apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: external-secrets
spec:
  refreshInterval: 1h             # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: test-secret    # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: test-secret
    remoteRef:
      key: test-secret      # name of the GCPSM secret key
