apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
  namespace: ui
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: oauth2-proxy
    creationPolicy: Owner
  data:
  - secretKey: oauth-client-id
    remoteRef:
      key: oauth-client-id
  - secretKey: oauth-client-secret
    remoteRef:
      key: oauth-client-secret
